# Taken from Firmament
[versions]
kotlin = "2.4.0"
fabric_kotlin = "1.13.12+kotlin.2.4.0"
fabric_loader = "0.19.3"
devauth = "1.2.2"

[libraries]
fabric_kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric_kotlin" }
fabric_loader = {module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader"}
devauth = { module = "me.djtheredstoner:DevAuth-fabric", version.ref = "devauth" }

[plugins]
kotlin_jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }